USE MASTER
GO

DROP DATABASE HQT
GO

CREATE DATABASE HQT
GO

USE HQT
GO

CREATE TABLE KHACHHANG (
	MaKH INT,
  	SDT CHAR(10) NOT NULL,
  	HoTen NVARCHAR(255) NOT NULL,
  	DiaChi NVARCHAR(255) NOT NULL,
  	NgaySinh DATETIME NOT NULL,
    NgayDangKy DATETIME NOT NULL,
  	MaPH INT,
  	MaNV INT,
  	PRIMARY KEY (MaKH)
)

CREATE TABLE PHANHANG (
	MaPH INT, 
  	TenPH NVARCHAR(255) NOT NULL,
  	TongMin INT,
  	TongMax INT,
  	PRIMARY KEY (MaPH)
)

CREATE TABLE LOAIPHIEUMUAHANG (
	MaLP INT,
  	MaPH INT NOT NULL,
  	TriGia INT NOT NULL,
  	PRIMARY KEY (MaLP)
)

CREATE TABLE PHIEUMUAHANG (
	MaPhieu INT, 
  	MaKH INT NOT NULL,
  	NgayTang DATETIME NOT NULL,
  	MaLP INT NOT NULL,
  	MaNV INT NOT NULL,
  	HanSuDung DATETIME,
  	TrangThai NVARCHAR(15) CHECK (TrangThai IN (N'Đã sử dụng', N'Chưa sử dụng', N'Hết hạn')),
	PRIMARY KEY (MaPhieu)
)

CREATE TABLE DANHMUC (
	MaDM INT,
  	TenDM NVARCHAR(255) NOT NULL,
  	PRIMARY KEY (MaDM)
)

CREATE TABLE SANPHAM (
	MaSP INT,
  	TenSP NVARCHAR(255) NOT NULL,
  	MoTa NVARCHAR(255),
  	GiaNiemYet INT NOT NULL,
  	SLToiDa INT NOT NULL,
  	SLTonKho INT NOT NULL,
  	DonVi NVARCHAR(255),
  	NgayThem DATETIME NOT NULL,
  	NgayCapNhat DATETIME NOT NULL,
  	MaDM INT NOT NULL,
  	MaNSX INT NOT NULL,
  	PRIMARY KEY (MaSP)
)

CREATE TABLE NHASANXUAT (
	MaNSX INT, 
  	TenNSX NVARCHAR(255) NOT NULL,
  	SDT CHAR(10) NOT NULL,
  	DiaChi NVARCHAR(255),
  	PRIMARY KEY (MaNSX)
)

CREATE TABLE BOPHAN (
	MaBP INT,
  	TenBP NVARCHAR(255) NOT NULL,
  	PRIMARY KEY (MaBP)
)

CREATE TABLE NHANVIEN (
	MaNV INT,
  	HoTen NVARCHAR(255) NOT NULL,
  	DiaChi NVARCHAR(255),
  	GioiTinh NVARCHAR(3),
  	SDT CHAR(10) NOT NULL,
  	CCCD CHAR(12) NOT NULL,
  	MaBP INT NOT NULL,
  	PRIMARY KEY (MaNV)
)

CREATE TABLE DONDATNSX (
	MaDDH INT, 
  	MaNSX INT NOT NULL,
  	SoLuong INT NOT NULL,
  	MaSP INT NOT NULL,
  	NgayDat DATETIME,
  	TinhTrang NVARCHAR(10) CHECK(TinhTrang IN (N'Chưa giao', N'Đã giao')),
  	MaNV INT NOT NULL,
  	PRIMARY KEY (MaDDH)
)

CREATE TABLE DONNHANHANG (
	MaDNH INT,
  	MaNV INT NOT NULL,
  	NgayNhan DATETIME,
  	TongTien INT,
  	MaNSX INT,
  	PRIMARY KEY (MaDNH)
)

CREATE TABLE CTDONNHANHANG (
	STT INT,
  	MaDNH INT,
  	SoLuong INT NOT NULL,
  	DonGia INT NOT NULL,
  	ThanhTien INT,
  	MaDDH INT,
  	PRIMARY KEY (MaDNH, STT)
)

CREATE TABLE DONHANG (
	MaDH INT,
  	NgayDat DATETIME,
  	NgayGiao DATETIME,
  	TinhTrang NVARCHAR(15) CHECK (TinhTrang IN (N'Đang xử lý', N'Đang vận chuyển', N'Đã giao', N'Đã hủy')),
  	ThanhTien INT NOT NULL,
  	TongPhaiTra INT NOT NULL,
  	MaPhieu INT,
  	MaNV INT NOT NULL,
  	MaKH INT,
  	PRIMARY KEY (MaDH)
)

CREATE TABLE CTDONHANG (
	MaDH INT,
  	STT INT,
  	MaSP INT NOT NULL,
  	SoLuong INT NOT NULL,
  	ThanhTien INT NOT NULL,
  	MaKhuyenMai INT,
  	TienPhaiTra INT NOT NULL,
  	PRIMARY KEY (MaDH, STT)
)

CREATE TABLE KHUYENMAI (
	MaKhuyenMai INT,
  	NgayBatDau DATETIME NOT NULL,
  	NgayKetThuc DATETIME NOT NULL,
  	NgayTaoMaKM DATETIME,
  	TiLe FLOAT NOT NULL,
  	SLToiDa INT NOT NULL,
  	TinhTrang NVARCHAR(15) CHECK (TinhTrang IN (N'Đang diễn ra', N'Kết thúc')), 
  	SLDaBan INT NOT NULL,
  	LoaiKM NVARCHAR(15) CHECK (LoaiKM IN ('Flash-sale', 'Combo-sale', 'Member-sale')),
  	MaNV INT NOT NULL,
  	PRIMARY KEY (MaKhuyenMai)
)

CREATE TABLE COMBOSALE (
	MaKhuyenMai INT,
  	MaSP1 INT NOT NULL,
  	MaSP2 INT NOT NULL,
  	PRIMARY KEY (MaKhuyenMai)
)

CREATE TABLE FLASHSALE (
	MaKhuyenMai INT,
  	MaSP INT NOT NULL,
  	PRIMARY KEY (MaKhuyenMai)
)

CREATE TABLE MEMBERSALE (
	MaKhuyenMai INT,
  	MaPH INT NOT NULL,
  	PRIMARY KEY (MaKhuyenMai)
)



ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_BOPHAN FOREIGN KEY (MaBP) REFERENCES BOPHAN(MaBP)

ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KHACHHANG_PHANHANG FOREIGN KEY (MaPH) REFERENCES PHANHANG(MaPH)

ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KHACHHANG_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)

ALTER TABLE LOAIPHIEUMUAHANG 
ADD CONSTRAINT FK_LOAIPHIEUMUAHANG_PHANHANG FOREIGN KEY (MaPH) REFERENCES PHANHANG(MaPH)

ALTER TABLE PHIEUMUAHANG
ADD CONSTRAINT FK_PHIEUMUAHANG_LOAIPHIEUMUAHANG FOREIGN KEY (MaLP) REFERENCES LOAIPHIEUMUAHANG(MaLP)

ALTER TABLE PHIEUMUAHANG
ADD CONSTRAINT FK_PHIEUMUAHANG_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)

ALTER TABLE PHIEUMUAHANG
ADD CONSTRAINT FK_PHIEUMUAHANG_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)

ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SANPHAM_DANHMUC FOREIGN KEY (MaDM) REFERENCES DANHMUC(MaDM)

ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SANPHAM_NHASANXUAT FOREIGN KEY (MaNSX) REFERENCES NHASANXUAT(MaNSX) 

ALTER TABLE KHUYENMAI
ADD CONSTRAINT FK_KHUYENMAI_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)

ALTER TABLE COMBOSALE
ADD CONSTRAINT FK_COMBOSALE_KHUYENMAI FOREIGN KEY (MaKhuyenMai) REFERENCES KHUYENMAI(MaKhuyenMai)

ALTER TABLE COMBOSALE
ADD CONSTRAINT FK_COMBOSALE_SANPHAM_1 FOREIGN KEY (MaSP1) REFERENCES SANPHAM(MaSP)

ALTER TABLE COMBOSALE
ADD CONSTRAINT FK_COMBOSALE_SANPHAM_2 FOREIGN KEY (MaSP2) REFERENCES SANPHAM(MaSP)

ALTER TABLE MEMBERSALE
ADD CONSTRAINT FK_MEMBERSALE_KHUYENMAI FOREIGN KEY (MaKhuyenMai) REFERENCES KHUYENMAI(MaKhuyenMai)

ALTER TABLE MEMBERSALE 
ADD CONSTRAINT FK_MEMBERSALE_PHANHANG FOREIGN KEY (MaPH) REFERENCES PHANHANG(MaPH)

ALTER TABLE FLASHSALE
ADD CONSTRAINT FK_FLASHSALE_KHUYENMAI FOREIGN KEY (MaKhuyenMai) REFERENCES KHUYENMAI(MaKhuyenMai)

ALTER TABLE FLASHSALE
ADD CONSTRAINT FK_FLASHSALE_SANPHAM FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_PHIEUMUAHANG FOREIGN KEY (MaPhieu) REFERENCES PHIEUMUAHANG(MaPhieu)

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)

ALTER TABLE CTDONHANG
ADD CONSTRAINT FK_CTDONHANG_SANPHAM FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)

ALTER TABLE CTDONHANG
ADD CONSTRAINT FK_CTDONHANG_DONHANG FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH)

ALTER TABLE CTDONHANG
ADD CONSTRAINT FK_CTDONHANG_KHUYENMAI FOREIGN KEY (MaKhuyenMai) REFERENCES KHUYENMAI(MaKhuyenMai)

ALTER TABLE DONDATNSX
ADD CONSTRAINT FK_DONDATNSX_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)

ALTER TABLE DONDATNSX
ADD CONSTRAINT FK_DONDATNSX_NHASANXUAT FOREIGN KEY (MaNSX) REFERENCES NHASANXUAT(MaNSX)

ALTER TABLE DONDATNSX
ADD CONSTRAINT FK_DONDATNSX_SANPHAM FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)

ALTER TABLE DONNHANHANG
ADD CONSTRAINT FK_DONNHANHANG_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)

ALTER TABLE DONNHANHANG
ADD CONSTRAINT FK_DONNHANHANG_NHASANXUAT FOREIGN KEY (MaNSX) REFERENCES NHASANXUAT(MaNSX)

ALTER TABLE CTDONNHANHANG
ADD CONSTRAINT FK_CTDONNHANHANG_DONNHANHANG FOREIGN KEY (MaDNH) REFERENCES DONNHANHANG(MaDNH)

ALTER TABLE CTDONNHANHANG
ADD CONSTRAINT FK_CTDONNHANHANG_DONDATNSX FOREIGN KEY (MaDDH) REFERENCES DONDATNSX(MaDDH)



